apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-suseconexample
  name: suseconexample-cd
  namespace: susecon-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-suseconexample
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-suseconexample
    spec:
      containers:
      - image: markusdhs/susecondemo:9d67692fab1c92926f5c2ab5703df510de284b35
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: test
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
