apiVersion: v1
kind: Service
metadata:
  name: suseconexample-service
  namespace: susecon-cd
spec:
  ports:
  - name: test
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-suseconexample
  type: ClusterIP
status:
  loadBalancer: {}
